### PR TITLE
Multi-language solved

### PR DESCRIPTION
**Pull request by domingoruiz**
After a lot of research I have found the problem and a solution to make the multilingual issue work with the new static page system.

The only way for it to work correctly is to have a file for each post and each language we have. I have researched and tried other ways but have not found another.

To facilitate the use of this solution I have created a couple of scripts. The first is new-language.sh. This ensures that when a new language is added to the system, all pages are cloned to the new language. The second is new-page.script.sh, which ensures that when we have a new page, it is cloned to all languages.

Maybe it is not the ideal solution, but it works, and it is the only one that allows us to use multi-language correctly in Hugo. 

Thank you.

### CODE REVIEW

**Comment by domingoruiz** [comment]
@ressonix How about it?

**Comment by hbjydev** [comment]
@domingoruiz We're reaching the point where manual translation is _way_ too difficult to maintain. There are far too many languages already supported, and trying to get people to translate our static content would just take **far** too long.

I think I'm going to close this PR (for one, it has no attached issue, so it doesn't meet our contribution guidelines, and for two, we need to think of a permanent solution before we write a couple of scripts to hack together a solution).

However, feel free to open an issue for this, as this is something we do eventually need to fix.

**Comment by domingoruiz** [comment]
I don't think he understood me. My intention is not to translate all the posts because that would be crazy. my only intention is that the site works well. Right now the posts do not work in any language, it only works in English, returning a 404 in the rest of the languages ​​and with this solution, which is the only one that hugo allows, it works the posts in all languages.

**Comment by hbjydev** [comment]
@domingoruiz Can you give me a URL example?

But still open an issue please, we need to meet the contribution guidelines.

**Comment by domingoruiz** [comment]
#146 read it

**Comment by hbjydev** [comment]
Alright. After a quick discussion with @ressonix, we've decided that we do _want_ a solution to this problem, but we're not sure a quick hacky fix is that solution.

We might revisit this later, but for now we're going to leave this. I'm keeping the issue on the tracker though.

**Comment by domingoruiz** [comment]
The problem is unsolved and must be solved. I've been reading Hugo's documentation looking for alternatives but this is the only one I found. If you find a better one, if none is found, we reopen this pull request, because as you have been able to check if it works. thanks.

**Comment by hbjydev** [comment]
Yes. It must be solved. That does not mean we will use this solution whether we find a better one or not.

**Pull request closed without merging**
