### PR TITLE
Feature: Add support languages ​​with xx_YY format

### PR DESCRIPTION
**Pull request by domingoruiz**
We have a problem with languages ​​that have the xx_YY format, so I think we should find a solution. I open the incident #77  since I am going to find a solution to this.

Thanks.

### CODE REVIEW

**Comment by dmarmelo** [comment]
I think the problem is that Hugo is treating the code string all lowercase, like "pt-pt" and the comparissons are being made with mixed case like "pt-PT".

**Comment by FoggyMtnDrifter** [comment]
Looks like there are some conflicts that need resolved. Go ahead and resolve those before we continue. @dmarmelo Can you test that this works for you?

**Comment by domingoruiz** [comment]
@ressonix it's solve.

**Comment by dmarmelo** [comment]
> Looks like there are some conflicts that need resolved. Go ahead and resolve those before we continue. @dmarmelo Can you test that this works for you?

No, it is still not working, but I've found a solution. Will open new PR.

**Comment by FoggyMtnDrifter** [comment]
I believe we're going with #81 as it's more optimized and requires a little less from the translators. Good work here, though!

**Pull request closed without merging**
