### PR TITLE
Fixed language redirect and made it dynamic.

### PR DESCRIPTION
**Pull request by dmarmelo**
Related #78.

### CODE REVIEW

**Comment by FoggyMtnDrifter** [comment]
This is much more efficient! I think if you and @domingoruiz can confirm it's both working for you, then we'll proceed with this one.

**Comment by dmarmelo** [comment]
There is still an issue with pt-br, I will try to solve it.

**Comment by FoggyMtnDrifter** [comment]
Alright, let's test it now. :))

**Comment by dmarmelo** [comment]
For me it's working fine!

**Pull request merged**
