### PR TITLE
added Turkish (tr) translation

### PR DESCRIPTION
**Pull request by sckn**
Turkish Language Support

### CODE REVIEW

**Review by hbjydev — CHANGES_REQUESTED** [review]
`tr.tom` needs to be `tr.toml`.

Also, you need to update the `vercel.json` and `config.toml` files accordingly. Examples of both exist in those files already.

**Comment by domingoruiz** [comment]
The language definition is missing in config.toml and in the javascript of layouts/partials/head/head.html

**Comment by domingoruiz** [comment]
@hbjydev Also the JavaScript Locate in layouts/partials/head/head.html for language detection.

**Comment by FoggyMtnDrifter** [comment]
Looks like we're officially good to go now @hbjydev

**Comment by sckn** [comment]
@domingoruiz @hbjydev Can you check please ? Is everything ok?

**Comment by domingoruiz** [comment]
Vercel failure in the verification process

**Comment by FoggyMtnDrifter** [comment]
That was for the previous changes @domingoruiz. @hbjydev has to authorize it before it will check again

**Review by FoggyMtnDrifter — APPROVED** [review]

**Comment by hbjydev** [comment]
Translations for the FAQ section are missing

**Comment by FoggyMtnDrifter** [comment]
I just noticed that, too

**Comment by domingoruiz** [comment]
It's great. Three languages ​​is fine, this is growing. I give my approval for its publication.

**Comment by domingoruiz** [comment]
By the way, I can help by checking the translation pull requests. Can you give me permission to do it? @ressonix @hbjydev

**Comment by FoggyMtnDrifter** [comment]
@domingoruiz We're still waiting on @sckn to update the FAQ sections before we merge. The FAQ sections are still in English.

**Comment by hbjydev** [comment]
https://wiki.rockylinux.org/en/Web/Website/contrib-i18n
Got this up for the purposes of future i18n efforts

**Comment by hbjydev** [comment]
@domingoruiz Look, I appreciate that you're trying to help, but these i18n aren't your responsibility, they're the web teams, i.e. mine currently.

We don't need you to approve/reject i18n from people, we can do that ourselves.

**Comment by domingoruiz** [comment]
Well, I would love to join that team. @hbjydev

**Comment by sckn** [comment]
I updated faq section.

**Comment by hbjydev** [comment]
@domingoruiz When there's an internationalisation team you'll no doubt be part of that, but for right now, leave the i18n stuff to me.

**Comment by sckn** [comment]
@hbjydev I read you document. Probably pass this time :)

**Comment by fabaff** [comment]
Related #33

**Comment by g3vxy** [comment]
There are some inconsistencies in Turkish translation when it comes to use of technical terms. For example "Bug-for-bug" and the translation of the words "upstream" and "downstream". Should we prefer keep the technical terms in English or should we translate them as well? If you ask for my opinion we should keep the English versions because literally no one uses the Turkish counterparts of those terms.

**Comment by FoggyMtnDrifter** [comment]
Can you take a look at #59 and provide your input there? Someone implemented some changes. @g3vxy

**Comment by bittin** [comment]
heh yeah, not sure the Swedish translation of those words are the best aswell, sorry for stealing your thread, but yeah would be nice if some other Swede want to look over my translations aswell

**Comment by g3vxy** [comment]
@ressonix i checked the PR and sadly it is not about the problem that i mentioned. I forked the project and i will try to fix the issue and create a new PR.

**Pull request merged**
