### PR TITLE
Revert "Added language check with country code where try are used."

### PR DESCRIPTION
**Pull request by dmarmelo**
Reverts rocky-linux/rockylinux.org#74

It is returning 404 again..

### CODE REVIEW

**Review by domingoruiz — APPROVED** [review]
That solution that was applied is a bit sloppy and does not work, it is better to reverse changes. I'm going to open an issue and look for a more elegant solution that works for all languages ​​with xx_YY format.

**Comment by FoggyMtnDrifter** [comment]
@dmarmelo It's working fine for me, can you double check your end? 

https://rockylinux-git-develop.rocky-linux.vercel.app/pt-pt/?l=pt-pt

**Comment by FoggyMtnDrifter** [comment]
If we can come up with a better solution, let's go for it. I'll merge the revert in the meantime.

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/78](https://github.com/rocky-linux/rockylinux.org/pull/78)

**Pull request merged**
