### PR TITLE
Solve bug with 404 page

### PR DESCRIPTION
**Pull request by domingoruiz**

### CODE REVIEW

**Comment by domingoruiz** [comment]
https://github.com/gohugoio/hugo/issues/3075

**Comment by hbjydev** [comment]
https://rockylinux-ooc8aj42e.vercel.app/es/udhuwdhu

PR hasn't fixed the problem.

**Comment by hbjydev** [comment]
(this PR is to work on issue #26)

**Comment by domingoruiz** [comment]
404 now works ok, before it did not work and it started to redirect. It appears in English due to a Hugo bug, that is, we will have to find some ugly solution to solve it temporarily. [gohugoio/hugo#3075](https://github.com/gohugoio/hugo/issues/3075)

**Pull request closed without merging**
