### PR TITLE
documentation improvements: update japanese translation more natural.

### LINKED ISSUE #124: Some Japanese translation are unnatural
There are some unnatural japanese.
e.g.
- "Forums" ->  "フォーラム". But "Forums" is correct because of proprietary noun.
- "So where does Rocky Linux come in?" -> "Rocky Linuxはどの場所に位置しますか？".
  This asks "Rocky Linux's location.", but correct meaning should be "Rocky Linux's role".

### PR DESCRIPTION
**Pull request by t-msyk**
Some unnatural japanese goes to natural japanese in this fix.
But some japanese are still unnatural.
Some improvements are needed.
I hope this help more :)

### CODE REVIEW

**Comment by hbjydev** [comment]
Did you find some Japanglish? Lol.

I'll review this soon.

**Comment by t-msyk** [comment]
Sorry for my github newbie.
I understand PR need linked Issue, but I done wrong operation.
How can i link this PR with this Issue.
"https://github.com/rocky-linux/rockylinux.org/issues/124#issue-767383269"

**Comment by hbjydev** [comment]
@t-msyk 

If you look on the right-hand side of the page, down towards the bottom of the sidebar there's a section marked "Linked issues".

**Comment by t-msyk** [comment]
Closes #124

**Comment by t-msyk** [comment]
no, no, no.
I make mistakes...orz

**Comment by t-msyk** [comment]
"Linked Issues" shows "none yet"
This means I'm failed to link this PR with issue #124, right?

**Pull request merged**
