### PR TITLE
Create a Contributors List

### PR DESCRIPTION
**Pull request by domingoruiz**
Hi. I have decided to create a list of contributors to give vision to all the people who are collaborating with the project and also to have located all the maintainers of the translations. I hope you think it's a good idea. I have started by putting my name, but everyone can put their own with a pull request.

Thanks.

Bye.

### CODE REVIEW

**Comment by FoggyMtnDrifter** [comment]
Going to get @hbjydev's input on this one since contributors are listed on the repo's front page already by default in GitHub. This seems like it might get a bit troublesome to maintain.

**Comment by domingoruiz** [comment]
@ressonix Contributors appear on the main github page, it is true, but this file can help us to know who is in charge of maintaining each language.

**Comment by fabaff** [comment]
I assume that sooner or later the l10n parts will be moved to a tool like [weblate](https://weblate.org/en/) or similar as we do for the [Fedora Project](https://translate.fedoraproject.org/). Most Open Source project do l10n and i18n this way because otherwise you need to have plenty of resources.

Keeping lists of people who are in charge up-to-date doesn't work in the long run. I have seen this a lot of time because the priorities of the involved persons can shift quickly.

**Comment by domingoruiz** [comment]
The ideal would be to use weblate, but I think the contributor list would be fine as a temporary solution. If we need to make changes to the web, how do you think if not to locate each of the translators?

Thanks.

**Comment by FoggyMtnDrifter** [comment]
Like @fabaff stated, the problem with the contribution list doesn't work in the long-term. We just got someone to create a PR for the Swedish translation and it looks like now they are suggesting someone else do it because they aren't confident in some parts of the translation. Translations are a big commitment, and we've already got quite a few disputes on some of them.

**Comment by hbjydev** [comment]
I'm going to close this PR, it isn't something we need. We have GitHub's contributing list and if I need to find the person maintaining a language I can use the Git history.

**Pull request closed without merging**
