### PR TITLE
Re-add portuguese language support.

### LINKED ISSUE #69: Portuguese translation needs new PR to be re-tested
After testing before making new changes live, we discovered that the Portuguese language resulted in a 404 error and wasn't immediately resolvable. Hugo gave the error, `WARN 2020/12/13 10:32:33 Failed to get translated string for language "pt"`. If you want to get this re-tested @dmarmelo, please do a new pull request to the `develop` branch with the translations so we can check it out.

### PR DESCRIPTION
**Pull request by dmarmelo**
Re-add portuguese language support #33.
As requested in #69.

### CODE REVIEW

**Comment by FoggyMtnDrifter** [comment]
Looks like this still results in a 404. It could be a Hugo bug. I'll start looking into this further, but for now we'll leave this here.

**Comment by dmarmelo** [comment]
For me when I try to access the page keeps redireting indefinetly like this: https://rockylinux-c8dug1dcy.vercel.app/pt/pt/pt/pt/pt/pt/pt/pt/pt/pt/pt/
And in the vercel logs it seems like hugo cannot get the translated strings.
I never used hugo I don't know if I'm doing something wrong..

**Comment by FoggyMtnDrifter** [comment]
Looks like that fixed it @dmarmelo. Great work!

**Comment by dmarmelo** [comment]
But there is still a problem, now it does note auto select the portuguese language because you are only checking the language and not the country code.

**Pull request merged**
