### PR TITLE
wip: feat: implement static content

### LINKED ISSUE #133: Static Content
**Is your feature request related to a problem? Please describe.**

We're reaching a point where we need to start having other pages and a blog of some sort.

**Describe the solution you'd like**

We need to implement a static content section of the page for blog posts, pages, etc. that Hugo will build for us with each release.

**Describe alternatives you've considered**

- A separate blog site that _isn't_ statically generated. (problem -- Security team don't think it's worth the trouble, and I agree)
- A headless CMS we can connect to from our frontend (problem -- would require JavaScript)

**Additional context**

There were discussions in our core channel about wanting a microblog or blog system of sorts for status updates, but being the core channel I can't link to that here.

### PR DESCRIPTION
**Pull request by hbjydev**
This still needs some work, which I'll be tracking on the this PR.

(Closes #133)

---

## Work Required

- [x] Development of single post layouts
- [x] Development of individual page layouts
- [x] RSS Feed for Posts
- [x] Pagination on index
- [x] First set of content (cc @rocky-linux/content)

### CODE REVIEW

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/issues/146](https://github.com/rocky-linux/rockylinux.org/issues/146)

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/157](https://github.com/rocky-linux/rockylinux.org/pull/157)

**Comment by hbjydev** [comment]
Ping @rocky-linux/content

**Comment by hbjydev** [comment]
@domingoruiz Could you backport your .json conversion into this branch?

**Comment by domingoruiz** [comment]
> @domingoruiz Could you backport your .json conversion into this branch?

Yes @hbjydev. This night I do It.

**Comment by domingoruiz** [comment]
> @domingoruiz Could you backport your .json conversion into this branch?

[https://github.com/rocky-linux/rockylinux.org/pull/181](https://github.com/rocky-linux/rockylinux.org/pull/181)

**Comment by hbjydev** [comment]
@ressonix Can you deal with the merge conflicts remaining? (404.html & index.html)

**Comment by FoggyMtnDrifter** [comment]
Done! 1de074ea1189d5a17300b82937e9a820f4daf17e

**Pull request merged**
